CREATE WAREHOUSE IF NOT EXISTS xs_warehouse
    WAREHOUSE_SIZE = XSMALL
    AUTO_RESUME = TRUE
    AUTO_SUSPEND = 60
    INITIALLY_SUSPENDED = TRUE;


CREATE [ OR REPLACE] WAREHOUSE [IF NOT EXISTS] <name>
   [ [WITH] objectproperties ]
   [objectparams];


objectproperties ::=
    WAREHOUSE_TYPE = STANDARD GEN 1 | STANDARD GEN 2 | SNOWPARK-OPTIMIZED
    WAREHOUSE_SIZE = XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE | X5LARGE | X6LARGE
    MIN_CLUSTER_COUNT = <num>
    MAX_CLUSTER_COUNT = <num>
    SCALING_POLICY = STANDARD | ECONOMY
    AUTO_SUSPEND = <num> | NULL
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    RESOURCE_MONITOR = <monitor_name>
    COMMENT = '<string_literal>'
    ENABLE_QUERY_ACCELERATION = TRUE | FALSE
    QUERY_ACCELERATION_MAX_SCALE_FACTOR = <num> 0--100

    objectparams ::=
    MAX_CONCURRENCY_LEVEL = <numn>
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = <num>
    STATEMENT_TIMEOUT_IN_SECONDS = <num>
    [[ WITH ] TAG (<tag_name> = '<tag_value>' [ ,<tag_name> = '<tag_value>',... ])];

    DROP WAREHOUSE IF EXISTS XS_WAREHOUSE;

    USE WAREHOUSE COMPUTE_WH;

    SHOW WAREHOUSES LIKE '%com%';
    